"""Initial migration

Revision ID: 025e19164d68
Revises: 
Create Date: 2025-03-10 15:13:39.479853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '025e19164d68'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('consumer_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('family_members', sa.Integer(), nullable=False),
    sa.Column('working_members', sa.Integer(), nullable=False),
    sa.Column('ages_of_working_members', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('consumer_number')
    )
    op.create_index(op.f('ix_users_consumer_number'), 'users', ['consumer_number'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('appliances',
    sa.Column('consumer_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('usage_hours', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_number'], ['users.consumer_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consumer_number', 'name')
    )
    op.create_table('bills',
    sa.Column('consumer_number', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('units_consumed', sa.Float(), nullable=False),
    sa.Column('cost_per_unit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['consumer_number'], ['users.consumer_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consumer_number', 'month')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bills')
    op.drop_table('appliances')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_consumer_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
